// Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"os"

	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "todolist app APIs",
	Description:      "todolist app api doc",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func Setup() {
	ts, err := os.ReadFile("docs/swagger.json")
	if err != nil {
		panic(err)
	}

	SwaggerInfo.SwaggerTemplate = string(ts)
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
