services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: passwordadmin
    ports:
      - 3326:3306
    volumes:
      - ./docker-volume/mysql:/var/lib/mysql
    networks:
      - todolist_net2

  api:
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=passwordadmin
      - MYSQL_DBNAME=todo4
    ports:
      - "3030:3030"
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - todolist_net2

networks:
  todolist_net2:
    name: todolist_net2